function [h, c] = linsep(pa, pb)
% Find a separating hyperplane betweens sets of points pa et pb
% (data points are arranged as columns in matrices pa and pb)
% Model: max 0 s.t. h^T ai + c <= -1 and h^t bi + c >= 1 

n = size(pa, 1);
na = size(pa, 2);
nb = size(pb, 2);
A = ...
c = ...
b = ...
K ...
[x,y,info]=sedumi(A, b, c, K);
h = ...
c = ...
if ...
    disp('There exists no separating hyperplane');
    h = []; c = [];
else
    disp(['Separating hyperplane: h=' mat2str(h,3) ' ; c=' num2str(c,3)]);
end
